from fpdf import FPDF
from datetime import datetime

class ReportPDF(FPDF):
    def header(self):
        # Logo / Seal placeholder text
        self.set_font("helvetica", "B", 16)
        self.cell(0, 10, "MAHARASHTRA CYBER POLICE", border=0, ln=1, align="C")
        self.set_font("helvetica", "B", 12)
        self.cell(0, 8, "INTELLIGENCE REPORT", border=0, ln=1, align="C")
        self.set_font("helvetica", "I", 10)
        self.cell(0, 6, "CONFIDENTIAL - RESTRICTED DISTRIBUTION", border=0, ln=1, align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Court-Admissible Digital Export", 0, 0, "C")

def generate_case_report(case: dict, transactions: list) -> bytes:
    pdf = ReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # Case Metadata
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "Case Details", ln=1)
    
    pdf.set_font("helvetica", "", 10)
    pdf.cell(50, 6, f"Case ID: {case.get('case_id', 'N/A')}", ln=0)
    pdf.cell(50, 6, f"Case Number: {case.get('case_number', 'N/A')}", ln=1)
    
    pdf.cell(50, 6, f"Title: {case.get('title', 'N/A')}", ln=0)
    pdf.cell(50, 6, f"Status: {str(case.get('status', 'N/A')).upper()}", ln=1)
    
    pdf.cell(50, 6, f"Priority: {str(case.get('priority', 'N/A')).upper()}", ln=0)
    pdf.cell(50, 6, f"Created: {case.get('created_at', 'N/A')[:10]}", ln=1)
    
    pdf.cell(50, 6, f"Total Volume: INR {case.get('total_amount', 0):,}", ln=0)
    pdf.cell(50, 6, f"Victim Count: {case.get('victim_count', 0)}", ln=1)
    
    pdf.ln(10)
    
    # Transactions Table
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "Evidence Log (Transactions)", ln=1)
    
    pdf.set_font("helvetica", "B", 9)
    col_widths = [30, 45, 45, 30, 20, 20]
    headers = ["Date", "From Account", "To Account", "Amount (INR)", "Mode", "Conf."]
    
    for i, header in enumerate(headers):
        pdf.cell(col_widths[i], 8, header, border=1, align="C")
    pdf.ln()

    pdf.set_font("helvetica", "", 8)
    for tx in transactions:
        pdf.cell(col_widths[0], 6, str(tx.get("timestamp", ""))[:10], border=1)
        pdf.cell(col_widths[1], 6, str(tx.get("from_account", "")), border=1)
        pdf.cell(col_widths[2], 6, str(tx.get("to_account", "")), border=1)
        pdf.cell(col_widths[3], 6, f"{tx.get('amount', 0):,}", border=1, align="R")
        pdf.cell(col_widths[4], 6, str(tx.get("type", "TRANSFER")), border=1, align="C")
        
        conf = tx.get("confidence")
        conf_str = f"{float(conf)*100:.0f}%" if conf is not None else "N/A"
        pdf.cell(col_widths[5], 6, conf_str, border=1, align="C")
        pdf.ln()

    pdf.ln(10)
    pdf.set_font("helvetica", "I", 9)
    pdf.multi_cell(0, 5, "This report has been automatically generated by the FraudLens Intelligence Network. All data contained herein has been cryptographically secured and traced from the source ingestion logs.")
    
    return pdf.output(dest="S")
